/*
 * flash.c
 *
 * Initial S25FL128L bring-up using ST's S25FL128S component driver.
 *
 * The original S25FL128S API names are intentionally retained to minimize
 * changes to the ST library.
 */

#include "flash.h"
#include "main.h"
#include "s25fl128s.h"

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

/*
 * QUADSPI handle generated by STM32CubeMX.
 *
 * This declaration is unnecessary if hqspi is already declared by a generated
 * quadspi.h file that you include instead.
 */
extern QSPI_HandleTypeDef hqspi;


/* Expected S25FL128L JEDEC identification bytes */
#define FLASH_EXPECTED_MANUFACTURER_ID    0x01U
#define FLASH_EXPECTED_MEMORY_TYPE_ID     0x60U
#define FLASH_EXPECTED_CAPACITY_ID        0x18U

/*
 * Final 4 KB sector of the 16 MB flash.
 *
 * Address range:
 * 0x00FFF000 to 0x00FFFFFF
 *
 * Reserve this sector for destructive testing.
 */

#define FLASH_TEST_DATA_SIZE 32U
#define FLASH_TEST_WRITE_ADDRESS   (EXT_FLASH_TEST_ADDRESS + 0xF0U)
#define FLASH_TEST_BUFFER_SIZE     300U

static bool flash_ready = false;


/**
 * @brief Print the current STM32 HAL QUADSPI state and error flags.
 *
 * @param stage Text identifying the point at which the information was read.
 */
static void flash_print_qspi_debug(const char *stage)
{
    printf(
        "[FLASH] %s | QSPI state: %lu | QSPI error: 0x%08lX\r\n",
        stage,
        (unsigned long)HAL_QSPI_GetState(&hqspi),
        (unsigned long)HAL_QSPI_GetError(&hqspi)
    );
}

bool flash_is_ready(void)
{
    return flash_ready;
}

/**
 * @brief Initialize and identify the S25FL128L.
 *
 * This first debugging version does not erase, program, or enter
 * memory-mapped mode.
 *
 * @retval HAL_OK    Flash reset and identification succeeded.
 * @retval HAL_ERROR A QSPI transaction failed or the ID did not match.
 */
HAL_StatusTypeDef flash_init(void)
{
    int32_t driver_status;
    uint8_t flash_id[3] = {0U, 0U, 0U};
    uint8_t status_reg1 = 0U;

    flash_ready = false;

    printf("\r\n");
    printf("[FLASH] Starting S25FL128L initialization...\r\n");

    flash_print_qspi_debug("Before initialization");

    /*
     * MX_QUADSPI_Init() must already have been called.
     */
    if (HAL_QSPI_GetState(&hqspi) != HAL_QSPI_STATE_READY)
    {
        printf("[FLASH] Error: QUADSPI peripheral is not ready.\r\n");
        flash_print_qspi_debug("Peripheral not ready");
        return HAL_ERROR;
    }

    /*
     * S25FL128L software reset sequence:
     *
     *     0x66 - Reset Enable
     *     0x99 - Software Reset
     *
     * These two flash commands must be consecutive. Do not insert another
     * QSPI transaction between them.
     */
    driver_status = S25FL128S_ResetEnable(
        &hqspi,
        S25FL128S_SPI_MODE
    );

    if (driver_status != S25FL128S_OK)
    {
        printf(
            "[FLASH] Reset Enable failed. Driver status: %ld\r\n",
            (long)driver_status
        );

        flash_print_qspi_debug("Reset Enable failure");
        return HAL_ERROR;
    }

    /*
     * Do not add a status-register read or another flash command before this.
     */
    driver_status = S25FL128S_ResetMemory(
        &hqspi,
        S25FL128S_SPI_MODE
    );

    if (driver_status != S25FL128S_OK)
    {
        printf(
            "[FLASH] Software Reset failed. Driver status: %ld\r\n",
            (long)driver_status
        );

        flash_print_qspi_debug("Software Reset failure");
        return HAL_ERROR;
    }

    /*
     * Give the flash time to complete its reset and reload volatile
     * configuration registers.
     */
    HAL_Delay(10U);

    printf("[FLASH] Software reset completed.\r\n");

    /*
     * Do not call S25FL128S_Enter4BytesAddressMode() here.
     *
     * The modified library either treats that function as a no-op, or the
     * application simply avoids calling it.
     */

    driver_status = S25FL128S_ReadID(
        &hqspi,
        S25FL128S_SPI_MODE,
        flash_id
    );

    if (driver_status != S25FL128S_OK)
    {
        printf(
            "[FLASH] JEDEC ID read failed. Driver status: %ld\r\n",
            (long)driver_status
        );

        flash_print_qspi_debug("Read ID failure");
        return HAL_ERROR;
    }

    printf(
        "[FLASH] JEDEC ID: %02X %02X %02X\r\n",
        flash_id[0],
        flash_id[1],
        flash_id[2]
    );

    /*
     * Expected S25FL128L ID:
     *
     *     01 = Infineon/Cypress manufacturer
     *     60 = FL-L memory type
     *     18 = 128-Mbit capacity
     */
    if ((flash_id[0] != FLASH_EXPECTED_MANUFACTURER_ID) ||
        (flash_id[1] != FLASH_EXPECTED_MEMORY_TYPE_ID) ||
        (flash_id[2] != FLASH_EXPECTED_CAPACITY_ID))
    {
        printf("[FLASH] Error: unexpected JEDEC ID.\r\n");

        printf(
            "[FLASH] Expected: %02X %02X %02X\r\n",
            FLASH_EXPECTED_MANUFACTURER_ID,
            FLASH_EXPECTED_MEMORY_TYPE_ID,
            FLASH_EXPECTED_CAPACITY_ID
        );

        flash_print_qspi_debug("JEDEC ID mismatch");
        return HAL_ERROR;
    }

    printf("[FLASH] S25FL128L identification passed.\r\n");

    /*
     * Read Status Register 1 for additional debugging.
     *
     * Only WIP and WEL are interpreted here because those two bits are common
     * to the operations currently being tested.
     */
    driver_status = S25FL128S_ReadStatusRegister(
        &hqspi,
        S25FL128S_SPI_MODE,
        &status_reg1
    );

    if (driver_status != S25FL128S_OK)
    {
        printf(
            "[FLASH] Status Register 1 read failed. Driver status: %ld\r\n",
            (long)driver_status
        );

        flash_print_qspi_debug("Status register failure");
        return HAL_ERROR;
    }

    printf(
        "[FLASH] Status Register 1: 0x%02X | WIP: %u | WEL: %u\r\n",
        status_reg1,
        ((status_reg1 & S25FL128S_SR1_WIP) != 0U) ? 1U : 0U,
        ((status_reg1 & S25FL128S_SR1_WREN) != 0U) ? 1U : 0U
    );

    /*
     * The flash should normally be idle and write-disabled after reset:
     *
     * WIP = 0
     * WEL = 0
     */
    if ((status_reg1 & S25FL128S_SR1_WIP) != 0U)
    {
        printf("[FLASH] Warning: flash reports that it is busy.\r\n");
    }

    flash_print_qspi_debug("Initialization complete");

    printf("[FLASH] Initialization succeeded.\r\n");
    flash_ready = true;
    return HAL_OK;
}



HAL_StatusTypeDef flash_read(
    uint32_t address,
    uint8_t *data,
    uint32_t size)
{
    int32_t driver_status;

    if (!flash_is_ready())
    {
        printf("[FLASH] Read rejected: flash is not ready.\r\n");
        return HAL_ERROR;
    }

    if ((data == NULL) || (size == 0U))
    {
        printf("[FLASH] Read rejected: invalid buffer or size.\r\n");
        return HAL_ERROR;
    }

    /*
     * Verify that the complete read stays within the 16 MB flash.
     *
     * Using subtraction avoids overflow from address + size.
     */
    if ((address >= EXT_FLASH_SIZE_BYTES) ||
        (size > (EXT_FLASH_SIZE_BYTES - address)))
    {
        printf(
            "[FLASH] Read rejected: address range is invalid. "
            "Address: 0x%08lX, size: %lu\r\n",
            (unsigned long)address,
            (unsigned long)size
        );

        return HAL_ERROR;
    }

    driver_status = S25FL128S_ReadSTR(
        &hqspi,
        S25FL128S_SPI_MODE,
        data,
        address,
        size
    );

    if (driver_status != S25FL128S_OK)
    {
        printf(
            "[FLASH] Read failed at 0x%08lX. Driver status: %ld\r\n",
            (unsigned long)address,
            (long)driver_status
        );

        flash_print_qspi_debug("Read failure");
        return HAL_ERROR;
    }

    return HAL_OK;
}


HAL_StatusTypeDef flash_write(
    uint32_t address,
    const uint8_t *data,
    uint32_t size)
{
    uint32_t page_offset;
    uint32_t page_space;
    uint32_t chunk_size;
    int32_t driver_status;

    if (!flash_is_ready())
    {
        printf("[FLASH] Write rejected: flash is not ready.\r\n");
        return HAL_ERROR;
    }

    if ((data == NULL) || (size == 0U))
    {
        printf("[FLASH] Write rejected: invalid buffer or size.\r\n");
        return HAL_ERROR;
    }

    /*
     * Verify that the complete write stays within the 16 MB flash.
     */
    if ((address >= EXT_FLASH_SIZE_BYTES) ||
        (size > (EXT_FLASH_SIZE_BYTES - address)))
    {
        printf(
            "[FLASH] Write rejected: address range is invalid. "
            "Address: 0x%08lX, size: %lu\r\n",
            (unsigned long)address,
            (unsigned long)size
        );

        return HAL_ERROR;
    }

    /*
     * A Page Program operation cannot cross a 256-byte page boundary.
     * Split the requested write into page-sized chunks.
     */
    while (size > 0U)
    {
        page_offset = address % EXT_FLASH_PAGE_SIZE;
        page_space = EXT_FLASH_PAGE_SIZE - page_offset;

        if (size < page_space)
        {
            chunk_size = size;
        }
        else
        {
            chunk_size = page_space;
        }

        /*
         * Every Page Program command requires a new Write Enable command.
         */
        driver_status = S25FL128S_WriteEnable(
            &hqspi,
            S25FL128S_SPI_MODE
        );

        if (driver_status != S25FL128S_OK)
        {
            printf(
                "[FLASH] Write Enable failed at 0x%08lX. "
                "Driver status: %ld\r\n",
                (unsigned long)address,
                (long)driver_status
            );

            flash_print_qspi_debug("Write Enable failure");
            return HAL_ERROR;
        }

        driver_status = S25FL128S_PageProgram(
            &hqspi,
            S25FL128S_SPI_MODE,
            (uint8_t *)data,
            address,
            chunk_size
        );

        if (driver_status != S25FL128S_OK)
        {
            printf(
                "[FLASH] Page Program failed at 0x%08lX. "
                "Driver status: %ld\r\n",
                (unsigned long)address,
                (long)driver_status
            );

            flash_print_qspi_debug("Page Program failure");
            return HAL_ERROR;
        }

        /*
         * Wait until the program operation completes and WIP becomes zero.
         */
        driver_status = S25FL128S_AutoPollingMemReady(
            &hqspi,
            S25FL128S_SPI_MODE
        );

        if (driver_status != S25FL128S_OK)
        {
            printf(
                "[FLASH] Program polling failed at 0x%08lX. "
                "Driver status: %ld\r\n",
                (unsigned long)address,
                (long)driver_status
            );

            flash_print_qspi_debug("Program polling failure");
            return HAL_ERROR;
        }

        address += chunk_size;
        data += chunk_size;
        size -= chunk_size;
    }

    return HAL_OK;
}


HAL_StatusTypeDef flash_erase_4k(uint32_t address)
{
    int32_t driver_status;

    printf(
        "[FLASH] Erase request at 0x%08lX\r\n",
        (unsigned long)address
    );

    if (!flash_is_ready())
    {
        printf("[FLASH] Erase rejected: flash is not ready.\r\n");
        return HAL_ERROR;
    }

    if (address >= EXT_FLASH_SIZE_BYTES)
    {
        printf("[FLASH] Erase rejected: address is outside flash.\r\n");
        return HAL_ERROR;
    }

    if ((address & (EXT_FLASH_SECTOR_SIZE_4K - 1UL)) != 0UL)
    {
        printf(
            "[FLASH] Erase rejected: address is not 4 KB aligned.\r\n"
        );
        return HAL_ERROR;
    }

    driver_status = S25FL128S_WriteEnable(
        &hqspi,
        S25FL128S_SPI_MODE
    );

    if (driver_status != S25FL128S_OK)
    {
        printf(
            "[FLASH] Erase Write Enable failed: %ld\r\n",
            (long)driver_status
        );
        return HAL_ERROR;
    }

    driver_status = S25FL128S_BlockErase(
        &hqspi,
        S25FL128S_SPI_MODE,
        address,
        S25FL128S_ERASE_4K
    );

    if (driver_status != S25FL128S_OK)
    {
        printf(
            "[FLASH] BlockErase failed: %ld\r\n",
            (long)driver_status
        );
        return HAL_ERROR;
    }

    driver_status = S25FL128S_AutoPollingMemReady(
        &hqspi,
        S25FL128S_SPI_MODE
    );

    if (driver_status != S25FL128S_OK)
    {
        printf(
            "[FLASH] Erase ready polling failed: %ld\r\n",
            (long)driver_status
        );
        return HAL_ERROR;
    }

    printf("[FLASH] 4 KB erase completed.\r\n");

    return HAL_OK;
}

